version: 0.0
os: linux
files:
  - source: /
    destination: /user/src/app
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "pras-nodejs-hello-world"
          ContainerPort: 8080
hooks:
  AfterInstall:
    - location: scripts/get_env_file.sh
      timeout: 300